config/routes.rb
Rails.application.routes.draw do
  
  get 'users/index'
  root 'pages#home'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :projects do
    resources :tasks
  end
  resources :tasks do
    collection do
      get :task_dashboard
    end
  end
  devise_for :users
  match '/users',   to: 'users#index',   via: 'get'
  match '/users/:id',     to: 'users#show',       via: 'get'
  resources :users, :only =>[:show]
  # root to: "projects#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end 

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  belongs_to :user, :optional => true


  validates :status, inclusion: { in: ['not-started', 'in-progress', 'complete'] }

  STATUS_OPTIONS = [
    ['Not started', 'not-started'],
    ['In progress', 'in-progress'],
    ['Complete', 'complete']
  ]

  def badge_color
    case status
    when 'not-started'
      'secondary'
    when 'in-progress'
      'info'
    when 'complete'
      'success'
    end
  end

  def complete?
    status == 'complete'
  end

  def in_progress?
    status == 'in-progress'
  end

  def not_started?
    status == 'not-started'
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController 
  before_action :authenticate_user!
  before_action :set_project
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  skip_before_action :set_project, only: [:task_dashboard]

  # GET projects/1/tasks
  def index
    @tasks = @project.tasks
  end

  def task_dashboard
    if current_user.present?
      if current_user.admin?
        @tasks = Task.includes(:user).where('start_time > ? and start_time <= ?', Date.today.at_beginning_of_day, Date.today.at_end_of_day).group_by{|i| i.user.name}
      else
        @tasks = Task.includes(:user).where('start_time > ? and start_time <= ?', Date.today.at_beginning_of_day, Date.today.at_end_of_day).where(user_id: current_user.id)
      end
    else
      redirect_to "/", notice: "Please sign in.."
    end
  end

  def all_task
    if current_user.present?
      @all_task = Task.find_by_user_id(@current_user.id)
      # render template: 'task/allTask'
    end
 end

  # GET projects/1/tasks/1
  def show
  end

  # GET projects/1/tasks/new
  def new
    @task = @project.tasks.build
  end

  # GET projects/1/tasks/1/edit
  def edit
  end

  # POST projects/1/tasks
  def create
    task_params_1 = task_params
    task_params_1[:user_id] = current_user.id
    @task = @project.tasks.build(task_params_1)

    if @task.save!
      redirect_to(@task.project)
    else
      render action: 'new'
    end
  end

  # PUT projects/1/tasks/1
  def update
    if @task.update_attributes(task_params)
      redirect_to(@task.project)
    else
      render action: 'edit'
    end
  end

  # DELETE projects/1/tasks/1
  def destroy
    @task.destroy

    redirect_to @project
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = current_user.projects.find(params[:project_id])
    end

    def set_task
      @task = @project.tasks.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def task_params
      params.require(:task).permit(:name, :description, :status, :project_id,:start_time, :end_time, :user_id)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for([@task.project, @task]) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br />
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br />
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :status %><br />
    <%= f.select :status, Task::STATUS_OPTIONS, {}, class: 'form-control' %>
  </div>
   <div class="form-group">
    <%= f.label :start_date %><br />
    <%= f.datetime_field :start_time, class: 'form-control' %>
  </div>
   <div class="form-group">
    <%= f.label :end_date %><br />
    <%= f.datetime_field :end_time, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<%= link_to 'Back', @project, class: 'btn btn-secondary mb-3' %>
<div class="card">
  <div class="card-body">
    <h2 class='card-title mb-4'>
      <span>Editing task</span>
    </h2>

    <%= render 'form' %>
  </div>
</div>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Status</th>
    <th>Project</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= task.name %></td>
    <td><%= task.description %></td>
    <td><%= task.status %></td>
    <td><%= task.project %></td>
    <td><%= link_to 'Show', [task.project, task] %></td>
    <td><%= link_to 'Edit', edit_project_task_path(task.project, task) %></td>
    <td><%= link_to 'Destroy x', [task.project, task], method: :delete, data: { turbo_method: :delete, confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task', new_project_task_path(params[:project_id]) %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>
<%= link_to 'Back', project_tasks_path(@task.project) %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @task.name %>
</p>

<p>
  <b>Description:</b>
  <%= @task.description %>
</p>

<p>
  <b>Status:</b>
  <%= @task.status %>
</p>

<p>
  <b>Project:</b>
  <%= @task.project %>
</p>


<%= link_to 'Edit', edit_project_task_path(@task.project, @task) %> |
<%= link_to 'Back', project_tasks_path(@task.project) %>

app/views/tasks/task_dashboard.html.erb
<h1>Today's Task</h1>
<% if current_user.admin? %>
    <% @tasks.each do |user, tasks| %>
    <h3><%= user %></h3>
    <ul>
        <% tasks.each do |task| %>
        <li>
            <h5><%= task.name %></h5>
            <p>
            <b>Description:</b> <%= task.description %></br>
            <b>Project:</b> <%= task.project.name %></br>
            <b>Status:</b> <%= task.status %>
            </p>
        </li>
        <% end %>
    </ul>
    <% end %>
<% else %>
    <h3>Welcome <%= current_user.name %></h3>
    <% @tasks.each do |task| %>
        <li>
            <h5><%= task.name %></h5>
            <p>
            <b>Description:</b> <%= task.description %></br>
            <b>Project:</b> <%= task.project.name %></br>
            <b>Status:</b> <%= task.status %>
            </p>
        </li>
    <% end %>
<% end %>