config/routes.rb
Rails.application.routes.draw do
  
  get 'users/index'
  root 'pages#home'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :projects do
    resources :tasks
  end
  resources :tasks do
    collection do
      get :task_dashboard
    end
  end
  devise_for :users
  match '/users',   to: 'users#index',   via: 'get'
  match '/users/:id',     to: 'users#show',       via: 'get'
  resources :users, :only =>[:show]
  # root to: "projects#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end 

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks, dependent: :destroy
  belongs_to :user

 
  def badge_color
    case status
    when 'not-started'
      'secondary'
    when 'in-progress'
      'info'
    when 'complete'
      'success'
    end
  end

  def status
    return 'not-started' if tasks.none?

    if tasks.all? { |task| task.complete? }
      'complete'
    elsif tasks.any? { |task| task.in_progress? || task.complete? }
      'in-progress'
    else
      'not-started'
    end
  end

  def percent_complete
    return 0 if tasks.none?
    ((total_complete.to_f / total_tasks) * 100).round
  end

  def total_complete
    tasks.select { |task| task.complete? }.count
  end

  def total_tasks
    tasks.count
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController 
  before_action :authenticate_user!
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = current_user.projects
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @task = @project.tasks.build
  end

  # GET /projects/new
  def new
    @project = current_user.projects.build
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.build(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = current_user.projects.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :description)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<%= link_to 'Back', @project, class: 'btn btn-secondary mb-3' %>
<div class="card">
  <div class="card-body">
    <h2 class='card-title mb-4'>
      <span>Editing project</span>
    </h2>

    <%= render 'form', project: @project %>
  </div>
</div>

app/views/projects/index.html.erb
<div class="card">
  <div class="card-body">
    <h2 class='card-title d-flex justify-content-between mb-4'>
      <span>Projects</span>
      <%= link_to 'New Project', new_project_path, class: 'btn btn-primary' %>
    </h2>

    <% @projects.each do |project| %>
      <%= link_to project, class: 'text-decoration-none' do %>
        <div class="card project-card mb-3">
          <div class="card-body">
            <div class="mb-3">
              <span class="badge badge-<%= project.badge_color %>">
                <%= project.status %>
              </span>
              <span class='text-secondary'>
                <small>
                  <%= project.percent_complete %>% complete
                  (<%= project.total_complete %>/<%= project.total_tasks %> tasks)
                </small>
              </span>
            </div>
            <h5 class='card-title text-dark'><b><%= project.name %></b></h5>
            <p class='text-secondary'><%= project.description %></p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/projects/new.html.erb
<%= link_to 'Back', projects_path, class: 'btn btn-secondary mb-3' %>
<div class="card">
  <div class="card-body">
    <h2 class='card-title mb-4'>
      <span>New project</span>
    </h2>

    <%= render 'form', project: @project %>
  </div>
</div>

app/views/projects/show.html.erb
<%= link_to 'Back', projects_path, class: 'btn btn-secondary mb-3' %>
<div class="card">
  <div class="card-body">
    <h2 class='card-title d-flex justify-content-between mb-4'>
      <span><%= @project.name %></span>
      <div>
        <%= link_to 'Edit', edit_project_path(@project), class: 'btn btn-light' %>
        <%= button_to 'Destroy', @project, method: :delete, class: 'btn btn-dark', data: { confirm: 'Are you sure?' } %>
      </div>
    </h2>

    <div class="mb-4">
      <h6>Add task</h6>
      <%= form_for([@task.project, @task]) do |f| %>
        <% if @task.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

            <ul>
            <% @task.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <%= f.hidden_field :status, value: 'not-started' %>
        <div class="input-group">
          <%= f.text_field :name, class: 'form-control', placeholder: 'Enter task name...' %>
           <%= f.text_area :description, class: 'form-control', placeholder: 'Description' %>
          <%= f.select :status, Task::STATUS_OPTIONS, {}, class: 'form-control', placeholder: 'Status' %>
          <%= f.datetime_field :start_time, class:'form-control',placeholder: ' task start_time...' %>
          <%= f.datetime_field :end_time, class: 'form-control',placeholder: ' task end_time ...' %>
          <div class="input-group-append">
            <%= f.submit class: 'btn btn-primary' %>
          </div>
        </div>
      <% end %>
    </div>

    <h4>Tasks</h4>
    <% @project.tasks.each do |task| %>
      <% if task.persisted? %>
        <div class="card mb-3">
          <div class="card-body">
            <div class="d-flex justify-content-between">
              <span class="badge badge-<%= task.badge_color %>"><%= task.status %></span>
              <div>
                <%= link_to 'Edit', edit_project_task_path(task.project, task), class: 'btn btn-light btn-sm' %>
                <%= button_to 'Destroy', project_task_path(task.project, task), method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: 'btn btn-dark btn-sm' %>
              </div>
            </div>
            <h5 class='card-title mb-2'>
              <span><%= task.name %></span>
            </h5>
            <p><%= task.description %></p>
          </div>
        </div>
      <% end %>
    <% end%>

  </div>
</div>